### PR TITLE
Travis setup

### PR DESCRIPTION
**Pull request by Tinawyn**
I setup travis-ci such that it builds without any tests

### CODE REVIEW

**Comment by roosemberth** [comment]
Can you please squash the last 3 commits into a single "change build tools version"?

**Comment by Tinawyn** [comment]
> Can you please squash the last 3 commits into a single "change build tools version"?

Well I tried and It didn't work I'm sorry I don't know how to do it ^^'

**Comment by roosemberth** [comment]
`git rebase -i HEAD~4` you squash (read the instructions) and then `git push origin travis-setup -f`

**Comment by roosemberth** [comment]
Give me a couple of minutes and I'll push the squashed commits to this branch

**Pull request merged**
